# Generated by Django 5.1.6 on 2025-03-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_expected_finish_alter_task_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expected_finish',
        ),
        migrations.RemoveField(
            model_name='task',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start',
        ),
    ]
