name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: cd crud_task_manager && poetry install --no-root

      - name: Run Linter (Ruff)
        run: cd crud_task_manager && poetry run ruff check .

      - name: Run Tests
        run: cd crud_task_manager && poetry run python manage.py test

      - name: Check for Missing Migrations
        run: cd crud_task_manager && poetry run python manage.py makemigrations --check --dry-run
